### ISSUE TITLE
Expose temporary folder where file are uploaded

### ISSUE THREAD

**Issue by mada199122** [dwaaan/HRConvert2-Docker#2]
Dear Dev,
Is it possible to expose as a volume the folder where the files are uploaded please?
Thanks

**Comment by zelon88** [comment]
Hello,

It is possible using mount binds. 
`mount -t none -o bind /home/converter /new/mount/location`
https://superuser.com/questions/663213/two-distinct-mount-points-with-one-device

**Comment by dwaaan** [comment]
Hi @zelon88, assuming files are uploaded into a directory that is not used by anything else, I can add this as a volume in the docker-compose file, let me know

**Comment by dwaaan** [comment]
added as optional in docker-compose.yml - just uncomment the line under volumes
